# CC3001 Primavera 2023 Tarea 2 -- Ignacio Romero Aravena

## Shellsort

### Profesores
Sección 1 Nelson Baloian/Patricio Poblete •
Sección 2 Benjamín Bustos •
Sección 3 Sebastián Ferrada


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_k,d_{k-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [1]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        insertar(a,k)

def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b

Probemos esto para asegurarnos que funcione bien:

In [2]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")

A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

In [3]:
def d_ordena_insercion(a,d):
    """d-Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        d_insertar(a,k,d)

def d_insertar(a,k,d):
    """
    Inserta a[k] entre los elementos anteriores a distancia d
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>d-1 and b<a[j-d]:
        a[j]=a[j-d]
        j-=d
    a[j]=b

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [4]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)
print(A)
verifica_d_ordenado(A,3)

[21 35 64 46 56 70 50 82 95 72]
Arreglo 3-ordenado OK.


## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_k=2^k-1$, esto es: $\ldots, 63, 31, 15, 7, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$. Su programa debe partir con el índice $k$ más grande tal que $d_k<n$.

In [5]:
def find_k(n):
#Función generada con ChatGPT
#Toma un entero n>0 y encuentra el valor de k más grande tal que d_k = (2**k)-1 < n
    k = 0
    while (2**k) - 1 < n:
        k += 1
    return k -1

#Test
assert(find_k(8)==3)
assert(find_k(2)==1)
assert(find_k(32)==5)
assert(find_k(100)==6)

In [6]:
def Shellsort(a):
    """Ordena a usando Shell Sort, con la secuencia de valores …,63,31,15,7,3,1"""
    n = len(a)
    k = find_k(n)
    for i in range(k,0,-1):
        d_i = (2**i)-1
        # print(d_i)
        d_ordena_insercion(a,d_i)
    return a

Pruebe aquí su algoritmo de la manera siguiente:

In [7]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
Shellsort(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [8]:
import random as rd
B = np.zeros(1000)
for j in range(1000):
    B[j]=(rd.randint(0,100000))
Shellsort(B)
verifica_d_ordenado(B,1)

Arreglo 1-ordenado OK.


## 3) Probar con una secuencia diferente de valores $d_k$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_k$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

Se vio en un estudio empírico [[1]](https://users.dcc.uchile.cl/~bebustos/files/Bus99.pdf), donde se analiza el rendimiento de diferentes series, que la serie $h_i = \frac{3^i - 1}{2} (... 9841, 3280, 1093, 364, 121, 40, 13, 4, 1)$ donde el paso mayor es el número de la serie tal que en donde el paso mayor es el número de la serie que se encuentra dos posiciones antes del más cercano a n, tiene el rendimiento más alto de las series analizadas.  

Así, al implementar el algoritmo con esta serie, se tiene que:

In [9]:
def find_i(n):
    # Toma un entero n>0 y encuentra el tercer valor de i más grande tal que h_i = {(3**i)-1}/2} < n
    # Para que se retorne siempre un número mayor o igual a 1, n>40. Es decir, como tiene que ser el tercer número más grande, si n<=40,
    #nos saldríamos del rango para h_i, es decir, tendríamos h_i menores a 1
    assert(n>40)
    i = 0
    while ((3**i)-1)/2 < n:
        i += 1
    return i - 4


# Test
assert(find_i(8000)==5)
assert(find_i(10000)==6)
assert(find_i(50)==1)
assert(find_i(41)==1)




In [10]:
def NewShellsort(a):
    # len(a) > 40 por el contrato de find_i
    assert(len(a)>40)
    n = len(a)
    k = find_i(n)
    for i in range(k,0,-1):
        d_i = int(((3**i)-1)/2)
        # print(d_i)
        d_ordena_insercion(a,d_i)
    return a

In [11]:
C = np.zeros(1000)
for j in range(1000):
    C[j]=(rd.randint(0,100000))
NewShellsort(C)
verifica_d_ordenado(C,1)

Arreglo 1-ordenado OK.


## ¿Qué hay que entregar?

Usted debe entregar este mismo archivo, modificado de acuerdo a lo que se pide. Haga todos los cambios necesarios para explicar y documentar adecuadamente su código. Cite todas las fuentes de información utilizadas. **No olvide poner su nombre en el encabezamiento**.